# Generated by Django 2.0 on 2019-03-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_lobo',
            new_name='company_logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='curator',
            new_name='creator',
        ),
    ]
