# Generated by Django 2.0 on 2019-03-22 11:38

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190318_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('details', tinymce.models.HTMLField(blank=True, default='')),
                ('mission', tinymce.models.HTMLField(blank=True, default='')),
                ('vission', tinymce.models.HTMLField(blank=True, default='')),
                ('mosaic', tinymce.models.HTMLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, default='about_us.jpg', null=True, upload_to='')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('designation', tinymce.models.HTMLField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('details', tinymce.models.HTMLField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
    ]
