# Generated by Django 2.0 on 2019-03-22 11:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutus_blog_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='key',
            field=autoslug.fields.AutoSlugField(default='cd', editable=False, populate_from='title'),
        ),
    ]
