# Generated by Django 2.0 on 2019-03-22 12:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190322_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='key',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['name', 'creation_date']),
        ),
    ]
