# Generated by Django 2.0 on 2019-03-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_clientreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='app.Company'),
        ),
    ]
