# Generated by Django 2.0 on 2019-03-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190323_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
    ]
