# Generated by Django 2.0 on 2019-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190323_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='descripsion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
