# Generated by Django 2.0 on 2019-03-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer_descripsion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='about_us.jpg', null=True, upload_to=''),
        ),
    ]
