# Generated by Django 2.0 on 2019-03-23 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190323_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 14, 18, 48, 435612)),
        ),
    ]
