# Generated by Django 2.0 on 2019-03-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190323_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('descripsion', models.TextField(blank=True, max_length=500, null=True)),
                ('backgroun_image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
    ]
